# Generated by Django 4.1.7 on 2023-03-13 05:16

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News_catagory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Catagory', models.CharField(blank=True, max_length=256, null=True)),
            ],
            options={
                'verbose_name_plural': 'News_catagory',
            },
        ),
        migrations.CreateModel(
            name='News_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=256, null=True)),
                ('subtitle', models.CharField(blank=True, max_length=256, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='news_image/')),
                ('Description', models.TextField(blank=True, max_length=256, null=True)),
                ('video_link', models.TextField(blank=True, max_length=256, null=True)),
                ('News_Date_Time', models.DateTimeField(blank=True, default=datetime.datetime(2023, 3, 13, 5, 16, 30, 94400))),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='news.news_catagory')),
            ],
            options={
                'verbose_name_plural': 'News',
            },
        ),
    ]
