# Generated by Django 4.1.3 on 2023-03-15 14:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0013_alter_news_model_news_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news_model',
            name='News_Date_Time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 3, 15, 20, 58, 13, 543221)),
        ),
    ]
