# Generated by Django 4.1.7 on 2023-03-13 05:15

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('User_info', '0002_alter_user_information_user_joing_date_time'),
        ('Player', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Team_Name', models.CharField(blank=True, max_length=256, null=True, unique=True)),
                ('Team_Owner_Name', models.CharField(blank=True, max_length=256, null=True)),
                ('Team_Total_play_count', models.IntegerField(default=0)),
                ('Win_count', models.IntegerField(default=0)),
                ('Loos_count', models.IntegerField(default=0)),
                ('Drow_count', models.IntegerField(default=0)),
                ('GF', models.IntegerField(default=0)),
                ('GA', models.IntegerField(default=0)),
                ('GD', models.IntegerField(default=0)),
                ('PTS', models.IntegerField(default=0)),
                ('Team_Official_Link', models.CharField(blank=True, max_length=256, null=True)),
                ('Team_Logo', models.ImageField(blank=True, null=True, upload_to='')),
                ('Team_banner', models.ImageField(blank=True, null=True, upload_to='')),
                ('Team_description', models.TextField(blank=True, null=True)),
                ('Team_Form_Date_Time', models.DateTimeField(blank=True, default=datetime.datetime(2023, 3, 13, 5, 15, 0, 996686))),
                ('Manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='User_info.user_information')),
                ('Team_captain', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Team_captain', to='Player.player_model')),
                ('Team_player_10_id_from_Plyer_model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='topic_content_type_all_10', to='Player.player_model')),
                ('Team_player_11_id_from_Plyer_model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='topic_content_type_all_11', to='Player.player_model')),
                ('Team_player_12_id_from_Plyer_model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='topic_content_type_all_12', to='Player.player_model')),
                ('Team_player_13_id_from_Plyer_model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='topic_content_type_all_13', to='Player.player_model')),
                ('Team_player_14_id_from_Plyer_model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='topic_content_type_all_14', to='Player.player_model')),
                ('Team_player_15_id_from_Plyer_model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='topic_content_type_all_15', to='Player.player_model')),
                ('Team_player_16_id_from_Plyer_model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='topic_content_type_all_16', to='Player.player_model')),
                ('Team_player_17_id_from_Plyer_model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='topic_content_type_all_17', to='Player.player_model')),
                ('Team_player_18_id_from_Plyer_model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='topic_content_type_all_18', to='Player.player_model')),
                ('Team_player_1_id_from_Plyer_model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='topic_content_type_all_1', to='Player.player_model')),
                ('Team_player_2_id_from_Plyer_model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='topic_content_type_all_2', to='Player.player_model')),
                ('Team_player_3_id_from_Plyer_model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='topic_content_type_all_3', to='Player.player_model')),
                ('Team_player_4_id_from_Plyer_model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='topic_content_type_all_4', to='Player.player_model')),
                ('Team_player_5_id_from_Plyer_model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='topic_content_type_all_5', to='Player.player_model')),
                ('Team_player_6_id_from_Plyer_model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='topic_content_type_all_6', to='Player.player_model')),
                ('Team_player_7_id_from_Plyer_model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='topic_content_type_all_7', to='Player.player_model')),
                ('Team_player_8_id_from_Plyer_model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='topic_content_type_all_8', to='Player.player_model')),
                ('Team_player_9_id_from_Plyer_model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='topic_content_type_all_9', to='Player.player_model')),
                ('Team_player_active_10_id_from_Plyer_model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='topic_content_type_ac_10', to='Player.player_model')),
                ('Team_player_active_11_id_from_Plyer_model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='topic_content_type_ac_11', to='Player.player_model')),
                ('Team_player_active_1_id_from_Plyer_model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='topic_content_type_ac_1', to='Player.player_model')),
                ('Team_player_active_2_id_from_Plyer_model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='topic_content_type_ac_2', to='Player.player_model')),
                ('Team_player_active_3_id_from_Plyer_model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='topic_content_type_ac_3', to='Player.player_model')),
                ('Team_player_active_4_id_from_Plyer_model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='topic_content_type_ac_4', to='Player.player_model')),
                ('Team_player_active_5_id_from_Plyer_model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='topic_content_type_ac_5', to='Player.player_model')),
                ('Team_player_active_6_id_from_Plyer_model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='topic_content_type_ac_6', to='Player.player_model')),
                ('Team_player_active_7_id_from_Plyer_model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='topic_content_type_ac_7', to='Player.player_model')),
                ('Team_player_active_8_id_from_Plyer_model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='topic_content_type_ac_8', to='Player.player_model')),
                ('Team_player_active_9_id_from_Plyer_model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='topic_content_type_ac_9', to='Player.player_model')),
                ('Team_player_substitute_1_id_from_Plyer_model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='topic_content_type_st_1', to='Player.player_model')),
                ('Team_player_substitute_2_id_from_Plyer_model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='topic_content_type_st_2', to='Player.player_model')),
                ('Team_player_substitute_3_id_from_Plyer_model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='topic_content_type_st_3', to='Player.player_model')),
                ('Team_player_substitute_4_id_from_Plyer_model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='topic_content_type_st_4', to='Player.player_model')),
                ('Team_player_substitute_5_id_from_Plyer_model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='topic_content_type_st_5', to='Player.player_model')),
                ('Team_player_substitute_6_id_from_Plyer_model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='topic_content_type_st_6', to='Player.player_model')),
                ('Team_player_substitute_7_id_from_Plyer_model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='topic_content_type_st_7', to='Player.player_model')),
            ],
            options={
                'verbose_name_plural': 'Team',
            },
        ),
    ]
