# Generated by Django 4.1.7 on 2023-03-13 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PLayer_Name', models.CharField(blank=True, max_length=256, null=True)),
                ('PLayer_Jersey', models.CharField(blank=True, max_length=256, null=True)),
                ('PLayer_Position', models.CharField(blank=True, max_length=256, null=True)),
                ('PLayer_Age', models.CharField(blank=True, max_length=256, null=True)),
                ('Total_goal_count', models.IntegerField(default=0)),
                ('Total_assist_count', models.IntegerField(default=0)),
                ('PLayer_Photo', models.ImageField(blank=True, null=True, upload_to='pLayer_photo/')),
                ('Base_price', models.CharField(blank=True, max_length=256, null=True)),
                ('Sell_price', models.CharField(blank=True, max_length=256, null=True)),
            ],
            options={
                'verbose_name_plural': 'Player',
            },
        ),
    ]
