# Generated by Django 4.1.7 on 2023-03-13 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Player', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='player_model',
            options={},
        ),
        migrations.AlterModelTable(
            name='player_model',
            table='Player',
        ),
    ]
