# Generated by Django 4.1.7 on 2023-03-13 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Player', '0002_alter_player_model_options_alter_player_model_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='player_model',
            name='Description',
            field=models.TextField(blank=True, max_length=256, null=True),
        ),
    ]
