# Generated by Django 4.1.3 on 2023-03-15 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Player', '0003_player_model_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='player_model',
            name='player_local_or_foreign',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
