# Generated by Django 4.1.7 on 2023-03-13 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Home_Team', models.CharField(blank=True, max_length=256, null=True)),
                ('Way_Team', models.CharField(blank=True, max_length=256, null=True)),
                ('Stadium_Name', models.CharField(blank=True, max_length=256, null=True)),
                ('Event_Logo', models.ImageField(blank=True, null=True, upload_to='event_image/')),
                ('is_game_finished', models.CharField(blank=True, max_length=256, null=True)),
                ('Event_Date_Time', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Event',
            },
        ),
    ]
