# Generated by Django 4.1.3 on 2023-03-15 14:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Game', '0012_alter_game_model_game_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game_model',
            name='Game_Date_Time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 3, 15, 20, 50, 18, 281360)),
        ),
    ]
