# Generated by Django 4.1.7 on 2023-03-15 17:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Game', '0015_alter_game_model_game_date_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='game_model',
            name='live_game_link',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='game_model',
            name='Game_Date_Time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 3, 15, 23, 12, 53, 779066)),
        ),
    ]
